# Site settings
title: This might work!
header-img: img/home-bg.png
email: johnram528@gmail.com
copyright_name: johnram528
description: > # this means to ignore newlines until "baseurl:"
  Maybe... Yes!!!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  johnram528
learn_profile: johnram528
email_username: johnram528@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
